# Generated by Django 5.2.12 on 2026-03-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', null=True),
        ),
    ]
